// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Sn9jB5JKWSJvGKuSj2HDTrpF2Hf6HF0',
    appId: '1:154962428188:web:5f53c51463ae927865bad9',
    messagingSenderId: '154962428188',
    projectId: 'gptgen-b08e6',
    authDomain: 'gptgen-b08e6.firebaseapp.com',
    storageBucket: 'gptgen-b08e6.appspot.com',
    measurementId: 'G-7ZTJ86X7ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUa73OFuaY8q5jOxY5VcYbGqj7GDLaM1c',
    appId: '1:154962428188:android:d4dc4a73b403634865bad9',
    messagingSenderId: '154962428188',
    projectId: 'gptgen-b08e6',
    storageBucket: 'gptgen-b08e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAorlTA6sYm5ddBnkOECJFj1ojAE8rwp0w',
    appId: '1:154962428188:ios:df9dcadeb0f5995365bad9',
    messagingSenderId: '154962428188',
    projectId: 'gptgen-b08e6',
    storageBucket: 'gptgen-b08e6.appspot.com',
    iosBundleId: 'com.cpad.gptgen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAorlTA6sYm5ddBnkOECJFj1ojAE8rwp0w',
    appId: '1:154962428188:ios:df9dcadeb0f5995365bad9',
    messagingSenderId: '154962428188',
    projectId: 'gptgen-b08e6',
    storageBucket: 'gptgen-b08e6.appspot.com',
    iosBundleId: 'com.cpad.gptgen',
  );
}
